on:

  push:

    branches:
    - main

    paths-ignore:
    - azure-pipelines-wpf.yml
    - .github/workflows/build-wpf.yml
    - src/DesktopClient/*
    - README.md
    - worker-README.md

jobs:
  Build_Worker: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ChannelName:
        - Release

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      BuildConfiguration: Release
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GitHubReleaseUrl: https://github.com/isaacrlevin/PresenceLight/releases/download
      Win10RID: net5.0-windows10.0.19041

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.3.1
      with:
        setCommonVars: true

    - run: echo "BuildNumber - ${{ env.GitBuildVersionSimple }}"

    - name: Create Directory for Channel
      run: mkdir ${{ github.workspace }}\${{ matrix.ChannelName }}
      shell: powershell


    - name: Publish signing scripts
      uses: actions/upload-artifact@v2
      with:
        path: Build
        name: SigningScripts
      if:  ${{ success() && matrix.ChannelName  == 'Release' }}

  Sign_Worker:
    needs: Build_Worker
    environment:
        name: Sign_Worker
        url: ${{ steps.deploy_staging.outputs.webapp-url }}
    name: Code Sign - CI
    runs-on: ubuntu-latest
    env:
      group: Sign Client Credentials
      if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: "${{ github.workspace }}/ToSign"

    - uses: actions/download-artifact@v2
      name: Download Signing Scripts Artifacts
      with:
        name: SigningScripts
        path: "${{ github.workspace }}/SigningScripts"

    - name: Install SignTool tool
      run: dotnet tool install --tool-path . SignClient

    - name: Scale Up Sign Service
      uses: azure/cli@v1.0.0
      with:
        inlineScript: az appservice plan update --name levin-signserv-asp-2dnwx6q6jwiay --resource-group SignService --sku P2V2
        azcliversion: latest

    - name: Authenticode Sign Zip
      run: |
        .\SignClient "Sign" `
        --baseDirectory "${{ github.workspace }}/ToSign" `
        --input "**/*.zip" `
        --config "${{ github.workspace }}/SigningScripts/appsettings.json" `
        --filelist "${{ github.workspace }}/SigningScripts/filelist.txt" `
        --user "${{ secrets.SignClientUser }}" `
        --secret "${{ secrets.SignClientSecret }}" `
        --name "PresenceLight" `
        --description "PresenceLight" `
        --descriptionUrl "https://github.com/isaacrlevin/PresenceLight"
      shell: pwsh

    - name: Scale Down Sign Service
      uses: azure/cli@v1.0.0
      with:
        inlineScript: az appservice plan update --name levin-signserv-asp-2dnwx6q6jwiay --resource-group SignService --sku S1
        azcliversion: latest